[2025-10-27T14:57:38.250+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T14:57:38.270+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T14:57:30.714200+00:00 [queued]>
[2025-10-27T14:57:38.276+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T14:57:30.714200+00:00 [queued]>
[2025-10-27T14:57:38.277+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T14:57:38.286+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-10-27 14:57:30.714200+00:00
[2025-10-27T14:57:38.293+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=396) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T14:57:38.294+0000] {standard_task_runner.py:64} INFO - Started process 398 to run task
[2025-10-27T14:57:38.295+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'transform_data', 'manual__2025-10-27T14:57:30.714200+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmpltm4rpkg']
[2025-10-27T14:57:38.296+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask transform_data
[2025-10-27T14:57:38.337+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.transform_data manual__2025-10-27T14:57:30.714200+00:00 [running]> on host a0076f556b70
[2025-10-27T14:57:38.406+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T14:57:30.714200+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T14:57:30.714200+00:00'
[2025-10-27T14:57:38.407+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T14:57:38.411+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T14:57:38.411+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: transform_data() missing 1 required positional argument: 'df'
[2025-10-27T14:57:38.419+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=mysql_to_postgres_etl, task_id=transform_data, run_id=manual__2025-10-27T14:57:30.714200+00:00, execution_date=20251027T145730, start_date=20251027T145738, end_date=20251027T145738
[2025-10-27T14:57:38.428+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task transform_data (transform_data() missing 1 required positional argument: 'df'; 398)
[2025-10-27T14:57:38.474+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-27T14:57:38.496+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-27T14:57:38.498+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
