[2025-10-27T14:57:32.104+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T14:57:32.122+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.test_connections manual__2025-10-27T14:57:30.714200+00:00 [queued]>
[2025-10-27T14:57:32.126+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.test_connections manual__2025-10-27T14:57:30.714200+00:00 [queued]>
[2025-10-27T14:57:32.127+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T14:57:32.137+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_connections> on 2025-10-27 14:57:30.714200+00:00
[2025-10-27T14:57:32.143+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=384) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T14:57:32.144+0000] {standard_task_runner.py:64} INFO - Started process 386 to run task
[2025-10-27T14:57:32.144+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'test_connections', 'manual__2025-10-27T14:57:30.714200+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmp4p932xbz']
[2025-10-27T14:57:32.145+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask test_connections
[2025-10-27T14:57:32.179+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.test_connections manual__2025-10-27T14:57:30.714200+00:00 [running]> on host a0076f556b70
[2025-10-27T14:57:32.240+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='test_connections' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T14:57:30.714200+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T14:57:30.714200+00:00'
[2025-10-27T14:57:32.241+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T14:57:32.247+0000] {base.py:84} INFO - Using connection ID '***_con' for task execution.
[2025-10-27T14:57:32.254+0000] {mysql_to_postgres_etl.py:20} INFO - MySQL connection test successful!
[2025-10-27T14:57:32.258+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T14:57:32.262+0000] {mysql_to_postgres_etl.py:28} INFO - PostgreSQL connection test successful!
[2025-10-27T14:57:32.262+0000] {python.py:237} INFO - Done. Returned value was: True
[2025-10-27T14:57:32.264+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T14:57:32.280+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=test_connections, run_id=manual__2025-10-27T14:57:30.714200+00:00, execution_date=20251027T145730, start_date=20251027T145732, end_date=20251027T145732
[2025-10-27T14:57:32.325+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T14:57:32.334+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
