[2025-10-27T15:09:10.176+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T15:09:10.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.run_data_quality_checks manual__2025-10-27T15:08:53.026563+00:00 [queued]>
[2025-10-27T15:09:10.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.run_data_quality_checks manual__2025-10-27T15:08:53.026563+00:00 [queued]>
[2025-10-27T15:09:10.202+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T15:09:10.212+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_data_quality_checks> on 2025-10-27 15:08:53.026563+00:00
[2025-10-27T15:09:10.219+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=162) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T15:09:10.220+0000] {standard_task_runner.py:64} INFO - Started process 164 to run task
[2025-10-27T15:09:10.220+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'run_data_quality_checks', 'manual__2025-10-27T15:08:53.026563+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmpi3ve5yx2']
[2025-10-27T15:09:10.221+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask run_data_quality_checks
[2025-10-27T15:09:10.257+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.run_data_quality_checks manual__2025-10-27T15:08:53.026563+00:00 [running]> on host a0076f556b70
[2025-10-27T15:09:10.328+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:08:53.026563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T15:08:53.026563+00:00'
[2025-10-27T15:09:10.330+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T15:09:10.338+0000] {base.py:84} INFO - Using connection ID '***_con' for task execution.
[2025-10-27T15:09:10.346+0000] {sql.py:495} INFO - Running statement: SELECT COUNT(*) FROM transactions, parameters: None
[2025-10-27T15:09:10.359+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T15:09:10.365+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:09:10.370+0000] {sql.py:495} INFO - Running statement: SELECT COUNT(*) FROM shipping_fact, parameters: None
[2025-10-27T15:09:10.379+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T15:09:10.386+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:09:10.389+0000] {sql.py:495} INFO - Running statement: 
        SELECT COUNT(*) 
        FROM shipping_fact 
        WHERE receipt_id IS NULL 
        OR customer_id IS NULL 
        OR last_status IS NULL
    , parameters: None
[2025-10-27T15:09:10.390+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T15:09:10.396+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:09:10.399+0000] {sql.py:495} INFO - Running statement: 
        SELECT COUNT(*) 
        FROM shipping_fact 
        WHERE last_status = 'done' 
        AND deleted_at IS NULL
    , parameters: None
[2025-10-27T15:09:10.408+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T15:09:10.409+0000] {mysql_to_postgres_etl.py:215} INFO - Data quality checks completed!
[2025-10-27T15:09:10.410+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-27T15:09:10.410+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T15:09:10.417+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=run_data_quality_checks, run_id=manual__2025-10-27T15:08:53.026563+00:00, execution_date=20251027T150853, start_date=20251027T150910, end_date=20251027T150910
[2025-10-27T15:09:10.441+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T15:09:10.454+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-27T15:09:10.456+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
