[2025-10-27T16:00:01.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T16:00:01.277+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.test_connections scheduled__2025-10-27T15:00:00+00:00 [queued]>
[2025-10-27T16:00:01.282+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.test_connections scheduled__2025-10-27T15:00:00+00:00 [queued]>
[2025-10-27T16:00:01.283+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T16:00:01.291+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_connections> on 2025-10-27 15:00:00+00:00
[2025-10-27T16:00:01.297+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1006) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T16:00:01.298+0000] {standard_task_runner.py:64} INFO - Started process 1008 to run task
[2025-10-27T16:00:01.299+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'test_connections', 'scheduled__2025-10-27T15:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmpu4v8hy4w']
[2025-10-27T16:00:01.299+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask test_connections
[2025-10-27T16:00:01.335+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.test_connections scheduled__2025-10-27T15:00:00+00:00 [running]> on host a0076f556b70
[2025-10-27T16:00:01.393+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='test_connections' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-27T15:00:00+00:00'
[2025-10-27T16:00:01.394+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T16:00:01.400+0000] {base.py:84} INFO - Using connection ID '***_con' for task execution.
[2025-10-27T16:00:01.406+0000] {mysql_to_postgres_etl.py:21} INFO - MySQL connection test successful!
[2025-10-27T16:00:01.411+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T16:00:01.414+0000] {mysql_to_postgres_etl.py:29} INFO - PostgreSQL connection test successful!
[2025-10-27T16:00:01.414+0000] {python.py:237} INFO - Done. Returned value was: True
[2025-10-27T16:00:01.415+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T16:00:01.432+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=test_connections, run_id=scheduled__2025-10-27T15:00:00+00:00, execution_date=20251027T150000, start_date=20251027T160001, end_date=20251027T160001
[2025-10-27T16:00:01.479+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T16:00:01.499+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-27T16:00:01.501+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
