[2025-10-27T17:47:07.341+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T17:47:07.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_to_postgres scheduled__2025-10-27T16:00:00+00:00 [queued]>
[2025-10-27T17:47:07.364+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_to_postgres scheduled__2025-10-27T16:00:00+00:00 [queued]>
[2025-10-27T17:47:07.364+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T17:47:07.373+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-10-27 16:00:00+00:00
[2025-10-27T17:47:07.378+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=89) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T17:47:07.379+0000] {standard_task_runner.py:64} INFO - Started process 91 to run task
[2025-10-27T17:47:07.379+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'load_to_postgres', 'scheduled__2025-10-27T16:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmp8b7w5f1w']
[2025-10-27T17:47:07.380+0000] {standard_task_runner.py:91} INFO - Job 93: Subtask load_to_postgres
[2025-10-27T17:47:07.414+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.load_to_postgres scheduled__2025-10-27T16:00:00+00:00 [running]> on host a0076f556b70
[2025-10-27T17:47:07.476+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-27T16:00:00+00:00'
[2025-10-27T17:47:07.478+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T17:47:07.521+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T17:47:07.532+0000] {mysql_to_postgres_etl.py:235} INFO - Successfully loaded 66 rows into PostgreSQL
[2025-10-27T17:47:07.532+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-27T17:47:07.532+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T17:47:07.539+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=load_to_postgres, run_id=scheduled__2025-10-27T16:00:00+00:00, execution_date=20251027T160000, start_date=20251027T174707, end_date=20251027T174707
[2025-10-27T17:47:07.559+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T17:47:07.574+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T17:47:07.576+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
