[2025-10-27T15:08:55.009+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T15:08:55.028+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.test_connections manual__2025-10-27T15:08:53.026563+00:00 [queued]>
[2025-10-27T15:08:55.033+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.test_connections manual__2025-10-27T15:08:53.026563+00:00 [queued]>
[2025-10-27T15:08:55.033+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T15:08:55.042+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_connections> on 2025-10-27 15:08:53.026563+00:00
[2025-10-27T15:08:55.048+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T15:08:55.050+0000] {standard_task_runner.py:64} INFO - Started process 98 to run task
[2025-10-27T15:08:55.050+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'test_connections', 'manual__2025-10-27T15:08:53.026563+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmp3brq4ve0']
[2025-10-27T15:08:55.051+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask test_connections
[2025-10-27T15:08:55.089+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.test_connections manual__2025-10-27T15:08:53.026563+00:00 [running]> on host a0076f556b70
[2025-10-27T15:08:55.161+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='test_connections' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:08:53.026563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T15:08:53.026563+00:00'
[2025-10-27T15:08:55.163+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T15:08:55.170+0000] {base.py:84} INFO - Using connection ID '***_con' for task execution.
[2025-10-27T15:08:55.178+0000] {mysql_to_postgres_etl.py:20} INFO - MySQL connection test successful!
[2025-10-27T15:08:55.184+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:08:55.188+0000] {mysql_to_postgres_etl.py:28} INFO - PostgreSQL connection test successful!
[2025-10-27T15:08:55.188+0000] {python.py:237} INFO - Done. Returned value was: True
[2025-10-27T15:08:55.189+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T15:08:55.209+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=test_connections, run_id=manual__2025-10-27T15:08:53.026563+00:00, execution_date=20251027T150853, start_date=20251027T150855, end_date=20251027T150855
[2025-10-27T15:08:55.231+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T15:08:55.253+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-27T15:08:55.255+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
