[2025-10-27T15:33:36.658+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T15:33:36.677+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_to_postgres manual__2025-10-27T15:33:29.332998+00:00 [queued]>
[2025-10-27T15:33:36.683+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_to_postgres manual__2025-10-27T15:33:29.332998+00:00 [queued]>
[2025-10-27T15:33:36.683+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T15:33:36.695+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-10-27 15:33:29.332998+00:00
[2025-10-27T15:33:36.700+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=525) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T15:33:36.701+0000] {standard_task_runner.py:64} INFO - Started process 527 to run task
[2025-10-27T15:33:36.702+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'load_to_postgres', 'manual__2025-10-27T15:33:29.332998+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmptyz7i4rl']
[2025-10-27T15:33:36.703+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask load_to_postgres
[2025-10-27T15:33:36.739+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.load_to_postgres manual__2025-10-27T15:33:29.332998+00:00 [running]> on host a0076f556b70
[2025-10-27T15:33:36.811+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:33:29.332998+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T15:33:29.332998+00:00'
[2025-10-27T15:33:36.813+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T15:33:36.861+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:33:36.911+0000] {mysql_to_postgres_etl.py:219} INFO - Successfully loaded 1000 rows into PostgreSQL
[2025-10-27T15:33:36.912+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-27T15:33:36.912+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T15:33:36.920+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=load_to_postgres, run_id=manual__2025-10-27T15:33:29.332998+00:00, execution_date=20251027T153329, start_date=20251027T153336, end_date=20251027T153336
[2025-10-27T15:33:36.964+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T15:33:36.981+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T15:33:36.983+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
