[2025-10-27T14:57:35.300+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T14:57:35.322+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.extract_from_mysql manual__2025-10-27T14:57:30.714200+00:00 [queued]>
[2025-10-27T14:57:35.329+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.extract_from_mysql manual__2025-10-27T14:57:30.714200+00:00 [queued]>
[2025-10-27T14:57:35.330+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T14:57:35.343+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2025-10-27 14:57:30.714200+00:00
[2025-10-27T14:57:35.349+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=390) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T14:57:35.350+0000] {standard_task_runner.py:64} INFO - Started process 392 to run task
[2025-10-27T14:57:35.351+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'extract_from_mysql', 'manual__2025-10-27T14:57:30.714200+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmppc10c0y1']
[2025-10-27T14:57:35.351+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask extract_from_mysql
[2025-10-27T14:57:35.394+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.extract_from_mysql manual__2025-10-27T14:57:30.714200+00:00 [running]> on host a0076f556b70
[2025-10-27T14:57:35.465+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T14:57:30.714200+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T14:57:30.714200+00:00'
[2025-10-27T14:57:35.467+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T14:57:35.475+0000] {base.py:84} INFO - Using connection ID '***_con' for task execution.
[2025-10-27T14:57:35.488+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:269: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2025-10-27T14:57:36.120+0000] {mysql_to_postgres_etl.py:86} INFO - Extracted 100000 rows from MySQL
[2025-10-27T14:57:36.121+0000] {python.py:237} INFO - Done. Returned value was:        receipt_id  customer_id  ...          updated_at          deleted_at
0             118         4708  ... 2025-10-16 22:19:43 2025-10-16 22:19:43
1             154           53  ... 2025-10-06 02:18:29                 NaT
2             274          220  ... 2025-10-13 23:26:47                 NaT
3             476         4781  ... 2025-10-28 11:08:25                 NaT
4             616         4005  ... 2025-11-05 06:20:56                 NaT
...           ...          ...  ...                 ...                 ...
99995       99662         4159  ... 2025-11-17 01:43:42                 NaT
99996       99708         2482  ... 2025-11-19 03:09:50                 NaT
99997       99771         2956  ... 2025-10-13 22:56:45 2025-10-13 22:56:45
99998       99927         2232  ... 2025-11-26 19:58:11                 NaT
99999       99971          864  ... 2025-11-19 17:40:03                 NaT

[100000 rows x 8 columns]
[2025-10-27T14:57:36.141+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T14:57:36.535+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=extract_from_mysql, run_id=manual__2025-10-27T14:57:30.714200+00:00, execution_date=20251027T145730, start_date=20251027T145735, end_date=20251027T145736
[2025-10-27T14:57:36.558+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T14:57:36.579+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T14:57:36.581+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
