[2025-10-27T17:47:08.429+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T17:47:08.445+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.run_data_quality_checks scheduled__2025-10-27T16:00:00+00:00 [queued]>
[2025-10-27T17:47:08.450+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.run_data_quality_checks scheduled__2025-10-27T16:00:00+00:00 [queued]>
[2025-10-27T17:47:08.450+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T17:47:08.459+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_data_quality_checks> on 2025-10-27 16:00:00+00:00
[2025-10-27T17:47:08.464+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T17:47:08.465+0000] {standard_task_runner.py:64} INFO - Started process 105 to run task
[2025-10-27T17:47:08.466+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'run_data_quality_checks', 'scheduled__2025-10-27T16:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmph6raoeaw']
[2025-10-27T17:47:08.467+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask run_data_quality_checks
[2025-10-27T17:47:08.499+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.run_data_quality_checks scheduled__2025-10-27T16:00:00+00:00 [running]> on host a0076f556b70
[2025-10-27T17:47:08.562+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='run_data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-27T16:00:00+00:00'
[2025-10-27T17:47:08.563+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T17:47:08.569+0000] {base.py:84} INFO - Using connection ID '***_con' for task execution.
[2025-10-27T17:47:08.575+0000] {sql.py:495} INFO - Running statement: SELECT COUNT(*) FROM transactions, parameters: None
[2025-10-27T17:47:08.588+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T17:47:08.593+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T17:47:08.596+0000] {sql.py:495} INFO - Running statement: SELECT COUNT(*) FROM shipping_fact, parameters: None
[2025-10-27T17:47:08.597+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T17:47:08.597+0000] {mysql_to_postgres_etl.py:251} WARNING - Record count mismatch: MySQL=100000, PostgreSQL=130
[2025-10-27T17:47:08.602+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T17:47:08.604+0000] {sql.py:495} INFO - Running statement: 
        SELECT COUNT(*) 
        FROM shipping_fact 
        WHERE receipt_id IS NULL 
        OR customer_id IS NULL 
        OR last_status IS NULL
    , parameters: None
[2025-10-27T17:47:08.605+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T17:47:08.609+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T17:47:08.612+0000] {sql.py:495} INFO - Running statement: 
        SELECT COUNT(*) 
        FROM shipping_fact 
        WHERE last_status = 'done' 
        AND deleted_at IS NULL
    , parameters: None
[2025-10-27T17:47:08.613+0000] {sql.py:504} INFO - Rows affected: 1
[2025-10-27T17:47:08.614+0000] {mysql_to_postgres_etl.py:282} INFO - Data quality checks completed!
[2025-10-27T17:47:08.614+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-27T17:47:08.614+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T17:47:08.621+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=run_data_quality_checks, run_id=scheduled__2025-10-27T16:00:00+00:00, execution_date=20251027T160000, start_date=20251027T174708, end_date=20251027T174708
[2025-10-27T17:47:08.645+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T17:47:08.657+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-27T17:47:08.659+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
