[2025-10-27T15:09:03.239+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T15:09:03.257+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_to_postgres manual__2025-10-27T15:08:53.026563+00:00 [queued]>
[2025-10-27T15:09:03.263+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.load_to_postgres manual__2025-10-27T15:08:53.026563+00:00 [queued]>
[2025-10-27T15:09:03.263+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-27T15:09:03.274+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-10-27 15:08:53.026563+00:00
[2025-10-27T15:09:03.280+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=132) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T15:09:03.282+0000] {standard_task_runner.py:64} INFO - Started process 134 to run task
[2025-10-27T15:09:03.283+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'load_to_postgres', 'manual__2025-10-27T15:08:53.026563+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmphqgzc8uq']
[2025-10-27T15:09:03.284+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask load_to_postgres
[2025-10-27T15:09:03.323+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.load_to_postgres manual__2025-10-27T15:08:53.026563+00:00 [running]> on host a0076f556b70
[2025-10-27T15:09:03.389+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T15:08:53.026563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T15:08:53.026563+00:00'
[2025-10-27T15:09:03.391+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T15:09:03.755+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:09:08.289+0000] {mysql_to_postgres_etl.py:175} INFO - Successfully loaded 100000 rows into PostgreSQL
[2025-10-27T15:09:08.318+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-27T15:09:08.318+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T15:09:08.326+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=load_to_postgres, run_id=manual__2025-10-27T15:08:53.026563+00:00, execution_date=20251027T150853, start_date=20251027T150903, end_date=20251027T150908
[2025-10-27T15:09:08.348+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T15:09:08.508+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T15:09:08.514+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
