[2025-10-27T15:00:22.098+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T15:00:22.117+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.test_connections scheduled__2025-10-27T13:00:00+00:00 [queued]>
[2025-10-27T15:00:22.122+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_postgres_etl.test_connections scheduled__2025-10-27T13:00:00+00:00 [queued]>
[2025-10-27T15:00:22.122+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-27T15:00:22.131+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_connections> on 2025-10-27 13:00:00+00:00
[2025-10-27T15:00:22.136+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=470) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-27T15:00:22.137+0000] {standard_task_runner.py:64} INFO - Started process 472 to run task
[2025-10-27T15:00:22.138+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_postgres_etl', 'test_connections', 'scheduled__2025-10-27T13:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_postgres_etl.py', '--cfg-path', '/tmp/tmpu2us_aep']
[2025-10-27T15:00:22.139+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask test_connections
[2025-10-27T15:00:22.172+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_postgres_etl.test_connections scheduled__2025-10-27T13:00:00+00:00 [running]> on host a0076f556b70
[2025-10-27T15:00:22.235+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_postgres_etl' AIRFLOW_CTX_TASK_ID='test_connections' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-27T13:00:00+00:00'
[2025-10-27T15:00:22.236+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T15:00:22.241+0000] {base.py:84} INFO - Using connection ID '***_con' for task execution.
[2025-10-27T15:00:22.250+0000] {mysql_to_postgres_etl.py:20} INFO - MySQL connection test successful!
[2025-10-27T15:00:22.254+0000] {base.py:84} INFO - Using connection ID 'postgres_con' for task execution.
[2025-10-27T15:00:22.258+0000] {mysql_to_postgres_etl.py:28} INFO - PostgreSQL connection test successful!
[2025-10-27T15:00:22.258+0000] {python.py:237} INFO - Done. Returned value was: True
[2025-10-27T15:00:22.259+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T15:00:22.276+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_postgres_etl, task_id=test_connections, run_id=scheduled__2025-10-27T13:00:00+00:00, execution_date=20251027T130000, start_date=20251027T150022, end_date=20251027T150022
[2025-10-27T15:00:22.318+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-27T15:00:22.341+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-27T15:00:22.343+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
